
<h2 class="header">Terms of Service.</h2>


<div class='tos-page'>
  <h3>The Basics</h3> 
  <div style="padding-bottom:30px;margin-bottom:30px;border-bottom:1px dashed #ccc;">
    <b>This webpage last updated 21 March, 2010.</b>
    <br/>Pluspanda.com is a small web based service that allows you to easily collect and display customer testimonials on your own website. Our basic plan is free, and we will be offering premium services for a small fee.
    To use pluspanda we ask that you be responsible and honest in how you use and with what you publish using Pluspanda.  In particular, make sure that none of the prohibited items listed below appear in any content stored on or being presented with Pluspanda (things like spam, viruses, or hate content).
    If we find an account holder to be in violation of these terms we have the right to terminate said user account.
    <br/><br/>
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/"><img src="http://creativecommons.org/images/public/somerights20.png" border="0" alt="Creative Commons License" align="right" /></a>
    The following Terms of Service is based on the work of <a href="http://wordpress.com">Wordpress</a> whom have generously made available under the Creative Commons Sharealike license. 
  </div> 
  
  <h3>Full Agreement</h3>
  <div>
    The following terms and conditions govern all use of the pluspanda.com website and all content, services and products available at or through the pluspanda website.  The Website is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies (including, without limitation, <a href="http://pluspanda.com/privacy_policy">Pluspanda's Privacy Policy</a>) and procedures that may be published from time to time on this Site by Pluspanda (collectively, the “Agreement”).
    <br/><br/>
    Please read this Agreement carefully before accessing or using the Website. By accessing or using any part of the web site, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access the Website or use any services. If these terms and conditions are considered an offer by Pluspanda, acceptance is expressly limited to these terms. The Website is available only to individuals who are at least 13 years old.
  </div> 
  
   
  <ol> 
  <li><strong>Your Pluspanda.com Account and Site.</strong> If you create an account on the Website, you are responsible for maintaining the security of your account and data, and you are fully responsible for all activities that occur under the account and any other actions taken in connection with the account. You must not describe or assign keywords to your data in a misleading or unlawful manner, including in a manner intended to trade on the name or reputation of others, and Pluspanda may change or remove any description or keyword that it considers inappropriate or unlawful, or otherwise likely to cause Pluspanda liability. You must immediately notify Pluspanda of any unauthorized uses of your account or data or any other breaches of security. Pluspanda will not be liable for any acts or omissions by You, including any damages of any kind incurred as a result of such acts or omissions.</li> 
  <li><strong>Responsibility of Contributors.</strong> If you operate any pluspanda widget, post data via the widget on external websites, or otherwise make (or allow any third party to make) material available by means of the Website and/or widgets (any such material, “Content”), You are entirely responsible for the content of, and any harm resulting from, that Content. That is the case regardless of whether the Content in question constitutes text, graphics, an audio file, or computer software. By making Content available, you represent and warrant that:
  <ul> 
  <li>the downloading, copying and use of the Content will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark or trade secret rights, of any third party;</li> 
  <li>if your employer has rights to intellectual property you create, you have either (i) received permission from your employer to post or make available the Content, including but not limited to any software, or (ii) secured from your employer a waiver as to all rights in or to the Content;</li> 
  <li>you have fully complied with any third-party licenses relating to the Content, and have done all things necessary to successfully pass through to end users any required terms;</li> 
  <li>the Content does not contain or install any viruses, worms, malware, Trojan horses or other harmful or destructive content;</li> 
  <li class="important">the Content is not spam, is not machine- or randomly-generated, and does not contain unethical or unwanted commercial content designed to drive traffic to third party sites or boost the search engine rankings of third party sites, or to further unlawful acts (such as phishing) or mislead recipients as to the source of the material (such as spoofing);</li> 
  <li>the Content is not pornographic, libelous or defamatory (<a href="http://www.eff.org/bloggers/lg/faq-defamation.php">more info on what that means</a>), does not contain threats or incite violence towards individuals or entities, and does not violate the privacy or publicity rights of any third party;</li> 
  <li>your content is not getting advertised via unwanted electronic messages such as spam links on newsgroups, email lists, other blogs and web sites, and similar unsolicited promotional methods;</li> 
  <li>your content is not named in a manner that misleads your readers into thinking that you are another person or company. For example, your testimonials&#8217;s URL or the names used are not deliberately or intentially fraudulent and/or meant to mislead; and</li> 
  <li>you have, in the case of Content that includes computer code, accurately categorized and/or described the type, nature, uses and effects of the materials, whether requested to do so by Pluspanda or otherwise.</li> 
  </ul> 
  <p>By submitting Content to Pluspanda for inclusion on your Website, you grant Pluspanda a world-wide, royalty-free, and non-exclusive license to reproduce, modify, adapt and publish the Content solely for the purpose of displaying, distributing and promoting your testimonials and/or widgets. If you delete Content, Pluspanda will use reasonable efforts to remove it from the Website, but you acknowledge that caching or references to the Content may not be made immediately unavailable.</p> 
  <p>Without limiting any of those representations or warranties, Pluspanda has the right (though not the obligation) to, in Pluspanda's sole discretion (i) refuse or remove any content that, in Pluspanda’s reasonable opinion, violates any Pluspanda policy or is in any way harmful or objectionable, or (ii) terminate or deny access to and use of the Website to any individual or entity for any reason, in Pluspanda’s sole discretion. Pluspanda will have no obligation to provide a refund of any amounts previously paid.</li> 
  <li><strong>TODO !! Fees and Payment.</strong> Optional premium paid services such as extra storage, domain purchases or VIP hosting are available on the Website. By selecting a premium service you agree to pay Pluspanda the monthly or annual subscription fees indicated for that service (the payment terms for VIP hosting are described below). Payments will be charged on the day you sign up for a premium service and will cover the use of that service for a monthly or annual period as indicated. Premium service fees are not refundable.</li> 
  <li><strong>VIP Services.</strong> 
  <ul> 
  <li><strong>Fees; Payment. </strong> By signing up for a VIP Services account you agree to pay Pluspanda the setup fees and monthly hosting fees indicated at <a href="http://wordpress.com/vip-hosting/">http://wordpress.com/vip-hosting/</a> in exchange for the services listed at <a href="http://wordpress.com/vip-hosting/">http://wordpress.com/vip-hosting/</a>. Applicable fees will be invoiced starting from the day your VIP Services are established and in advance of using such services.  Pluspanda reserves the right to change the payment terms and fees upon thirty (30) days prior written notice to you.  VIP Services can be canceled by you at anytime on 30 days written notice to Pluspanda.</li> 
  <li><strong>Support.</strong> VIP Services include access to priority email support.  “Email support” means the ability to make requests for technical support assistance by email at any time (with reasonable efforts by Pluspanda to respond within one business day) concerning the use of the VIP Services.  “Priority” means that support for VIP Services customers takes priority over support for users of the standard, free Pluspanda.com blogging services.  All VIP Services support will be provided in accordance with Pluspanda standard VIP Services practices, procedures and policies.</li> 
  </ul> 
  </li> 
  <li><strong>Responsibility of Website Visitors.</strong> Pluspanda has not reviewed, and cannot review, all of the material, including computer software, posted to the Website, and cannot therefore be responsible for that material’s content, use or effects. By operating the Website, Pluspanda does not represent or imply that it endorses the material there posted, or that it believes such material to be accurate, useful or non-harmful. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. The Website may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. The Website may also contain material that violates the privacy or publicity rights, or infringes the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which is subject to additional terms and conditions, stated or unstated. Pluspanda disclaims any responsibility for any harm resulting from the use by visitors of the Website, or from any downloading by those visitors of content there posted.</li> 
  <li><strong>Content Posted on Other Websites.</strong> We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and webpages to which Pluspanda.com links, and that link to Pluspanda.com. Pluspanda does not have any control over those non-Pluspanda websites and webpages, and is not responsible for their contents or their use. By linking to a non-Pluspanda website or webpage, Pluspanda does not represent or imply that it endorses such website or webpage. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. Pluspanda disclaims any responsibility for any harm resulting from your use of non-Pluspanda websites and webpages.</li> 
  <li><strong>Copyright Infringement and DMCA Policy.</strong> As Pluspanda asks others to respect its intellectual property rights, it respects the intellectual property rights of others. If you believe that material located on or linked to by Pluspanda.com violates your copyright, you are encouraged to notify Pluspanda by emailing <a href="mailto:plusjade@gmail.com">plusjade@gmail.com</a>. Pluspanda will respond to all such notices, including as required or appropriate by removing the infringing material or disabling all links to the infringing material. In the case of a visitor who may infringe or repeatedly infringes the copyrights or other intellectual property rights of Pluspanda or others, Pluspanda may, in its discretion, terminate or deny access to and use of the Website. In the case of such termination, Pluspanda will have no obligation to provide a refund of any amounts previously paid to Pluspanda.</li> 
  <li><strong>Intellectual Property.</strong> This Agreement does not transfer from Pluspanda to you any Pluspanda or third party intellectual property, and all right, title and interest in and to such property will remain (as between the parties) solely with Pluspanda.  Pluspanda, Pluspanda.com, the Pluspanda.com logo, and all other trademarks, service marks, graphics and logos used in connection with Pluspanda.com, or the Website are trademarks or registered trademarks of Pluspanda or Pluspanda’s licensors. Other trademarks, service marks, graphics and logos used in connection with the Website may be the trademarks of other third parties. Your use of the Website grants you no right or license to reproduce or otherwise use any Pluspanda or third-party trademarks.</li> 
  <li><strong>Changes. </strong>Pluspanda reserves the right, at its sole discretion, to modify or replace any part of this Agreement.  It is your responsibility to check this Agreement periodically for changes. Your continued use of or access to the Website following the posting of any changes to this Agreement constitutes acceptance of those changes.  Pluspanda may also, in the future, offer new services and/or features through the Website (including, the release of new tools and resources).  Such new features and/or services shall be subject to the terms and conditions of this Agreement. <strong><br /> 
  </strong></li> 
  <li><strong>Termination. </strong>Pluspanda may terminate your access to all or any part of the Website at any time, with or without cause, with or without notice, effective immediately.  If you wish to terminate this Agreement or your Pluspanda.com account (if you have one), you may simply discontinue using the Website.  Notwithstanding the foregoing, if you have a (todo)VIP Services account, such account can only be terminated by Pluspanda if you materially breach this Agreement and fail to cure such breach within thirty (30) days from Pluspanda’s notice to you thereof; provided that, Pluspanda can terminate the Website immediately as part of a general shut down of our service.  All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability. <strong><br /> 
  </strong></li> 
  <li class="important"><strong>Disclaimer of Warranties.</strong> The Website is provided &#8220;as is&#8221;. Pluspanda and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither Pluspanda nor its suppliers and licensors, makes any warranty that the Website will be error free or that access thereto will be continuous or uninterrupted.  You understand that you download from, or otherwise obtain content or services through, the Website at your own discretion and risk.</li> 
  <li class="important"><strong>Limitation of Liability.</strong> In no event will Pluspanda, or its suppliers or licensors, be liable with respect to any subject matter of this agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement or substitute products or services; (iii) for interruption of use or loss or corruption of data; or (iv) for any amounts that exceed the fees paid by you to Pluspanda under this agreement during the twelve (12) month period prior to the cause of action. Pluspanda shall have no liability for any failure or delay due to matters beyond their reasonable control. The foregoing shall not apply to the extent prohibited by applicable law.</li> 
  <li><strong>General Representation and Warranty.</strong> You represent and warrant that (i) your use of the Website will be in strict accordance with the Pluspanda Privacy Policy, with this Agreement and with all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the United States or the country in which you reside) and (ii) your use of the Website will not infringe or misappropriate the intellectual property rights of any third party.</li> 
  <li><strong>Indemnification.</strong> You agree to indemnify and hold harmless Pluspanda, its contractors, and its licensors, and their respective directors, officers, employees and agents from and against any and all claims and expenses, including attorneys’ fees, arising out of your use of the Website, including but not limited to your violation of this Agreement.</li> 
  <li><strong>Miscellaneous.</strong> This Agreement constitutes the entire agreement between Pluspanda and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of Pluspanda, or by the posting by Pluspanda of a revised version. Except to the extent applicable law, if any, provides otherwise, this Agreement, any access to or use of the Website will be governed by the laws of the state of California, U.S.A., excluding its conflict of law provisions, and the proper venue for any disputes arising out of or relating to any of the same will be the state and federal courts located in Los Angeles County, California.  Except for claims for injunctive or equitable relief or claims regarding intellectual property rights (which may be brought in any competent court without the posting of a bond), any dispute arising under this Agreement shall be finally settled in accordance with the Comprehensive Arbitration Rules of the Judicial Arbitration and Mediation Service, Inc. (“JAMS”) by three arbitrators appointed in accordance with such Rules.  The arbitration shall take place in Los Angeles, California, in the English language and the arbitral decision may be enforced in any court.  The prevailing party in any action or proceeding to enforce this Agreement shall be entitled to costs and attorneys’ fees.  If any part of this Agreement is held invalid or unenforceable, that part will be construed to reflect the parties’ original intent, and the remaining portions will remain in full force and effect. A waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; Pluspanda may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.</li> 
  </ol> 
</div> 











